# Generated by Django 6.0.7 on 2026-09-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('pan', models.CharField(blank=True, max_length=30, null=True)),
                ('client_code', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=25, null=True)),
                ('logo', models.FileField(default=True, null=True, upload_to='images/logo/')),
                ('sign', models.FileField(default=True, null=True, upload_to='images/sign/')),
                ('stamp', models.FileField(default=True, null=True, upload_to='images/stamp/')),
                ('company_id', models.PositiveIntegerField(default=0, null=True)),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.fiscalyear')),
            ],
        ),
    ]
