# Generated by Django 6.0.7 on 2026-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(default=0, null=True)),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_client_dashboard', models.BooleanField(default=False)),
                ('status', models.CharField(default='Not Assigned', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
