ROLES_CONFIG = {
    "Admin": [
        # User permissions
        "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",

        # Group permissions
        "add_group", "change_group", "delete_group", "view_group",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",



        # Client Registration
        "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",


        # Log Entry permissions
        "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",

        # Verification Record permissions
        "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",
   ],

    "Manager": [
        # User permissions
          "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",
         
        # Client Registration
        "add_user", "change_user", "delete_user", "view_user",
        "add_logentry","change_logentry", "delete_logentry", "view_logentry","add_permission",
        "add_permission", "change_permission", "delete_permission", "view_permission",
        "add_group","change_group", "delete_group", "view_group",
        "add_contenttype","change_contenttype", "delete_contenttype", "view_contenttype",
        "add_session","change_session","delete_session", "view_session",
        "add_auditlog", "change_auditlog", "delete_auditlog", "view_auditlog",
        "add_verificationrecord", "change_verificationrecord","delete_verificationrecord", "view_verificationrecord",
        "add_tdssection", "change_tdssection", "delete_tdssection", "view_tdssection",
        "add_tdsbooking", "change_tdsbooking", "delete_tdsbooking", "view_tdsbooking",
        "add_clientregistration", "change_clientregistration", "delete_clientregistration", "view_clientregistration",
        "add_complianceeventvat", "change_complianceeventvat", "delete_complianceeventvat", "view_complianceeventvat",
        "add_notice","change_notice", "delete_notice", "view_notice",
        "add_fiscalyear","change_fiscalyear", "delete_fiscalyear", "view_fiscalyear",
        "add_company","change_company", "delete_company", "view_company",
        "add_dashboardconfigurations", "change_dashboardconfigurations", "delete_dashboardconfigurations", "view_dashboardconfigurations",
        "add_assetregistration","change_assetregistration", "delete_assetregistration", "view_assetregistration",
        "add_expenseitem","change_expenseitem", "delete_expenseitem", "view_expenseitem",
        "add_assetsblock", "change_assetsblock", "delete_assetsblock", "view_assetsblock",
        "add_assetscategory","change_assetscategory", "delete_assetscategory", "view_assetscategory",
        "add_bsmonth", "change_bsmonth", "delete_bsmonth", "view_bsmonth",
        "add_vatadjustmentreportrecord", "change_vatadjustmentreportrecord", "delete_vatadjustmentreportrecord", "view_vatadjustmentreportrecord",
        "add_taxvoucherrecord", "change_taxvoucherrecord", "delete_taxvoucherrecord", "view_taxvoucherrecord",
        "add_balancecms", "change_balancecms", "delete_balancecms", "view_balancecms",
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
        "add_vendor", "change_vendor", "delete_vendor", "view_vendor",
        "add_customer", "change_customer", "delete_customer", "view_customer",
        "add_vatreturn", "change_vatreturn", "delete_vatreturn", "view_vatreturn",
        "add_openingaccounttax", "change_openingaccounttax", "delete_openingaccounttax", "view_openingaccounttax",
        "add_roles", "change_roles", "delete_roles", "view_roles",
        "add_user", "change_user", "delete_user", "view_user"
        "add_bankname", "change_bankname", "delete_bankname", "view_bankname",
        "add_previousyearadjustment", "change_previousyearadjustment", "delete_previousyearadjustment", "view_previousyearadjustment",
        "add_interestfinerecord", "change_interestfinerecord", "delete_interestfinerecord", "view_interestfinerecord",
        "add_creditadjustment", "change_creditadjustment", "delete_creditadjustment", "view_creditadjustment",
        "add_billmissedadjustment", "change_billmissedadjustment", "delete_billmissedadjustment", "view_billmissedadjustment",
        "add_arithmeticerroradjustment", "change_arithmeticerroradjustment", "delete_arithmeticerroradjustment", "view_arithmeticerroradjustment",
        "add_chartofaccount", "change_chartofaccount", "delete_chartofaccount", "view_chartofaccount",
        "add_journalentry", "change_journalentry", "delete_journalentry", "view_journalentry",
        "add_journalitem", "change_journalitem", "delete_journalitem", "view_journalitem",
        "add_country", "change_country", "delete_country", "view_country",
        "add_district", "change_district", "delete_district", "view_district",
        "add_municipality", "change_municipality", "delete_municipality", "view_municipality",
        "add_state", "change_state", "delete_state", "view_state",
        "add_taxoffice", "change_taxoffice", "delete_taxoffice", "view_taxoffice",
        "add_unit", "change_unit", "delete_unit", "view_unit",
        "add_stockitem", "change_stockitem", "delete_stockitem", "view_stockitem",
        "add_documentrecord", "change_documentrecord", "delete_documentrecord", "view_documentrecord",
        "add_documenttype", "change_documenttype", "delete_documenttype", "view_documenttype",
        "add_activity", "change_activity", "delete_activity", "view_activity",
        "add_actversion", "change_actversion", "delete_actversion", "view_actversion",
        "add_tag", "change_tag", "delete_tag", "view_tag",
        "add_section", "change_section", "delete_section", "view_section",
        "add_rule", "change_rule", "delete_rule", "view_rule",
        "add_directive", "change_directive", "delete_directive", "view_directive",
        "add_case", "change_case", "delete_case", "view_case",
        "add_casesection", "change_casesection", "delete_casesection", "view_casesection",
        "add_bankaccount", "change_bankaccount", "delete_bankaccount", "view_bankaccount",
        "add_matchrule", "change_matchrule", "delete_matchrule", "view_matchrule",
        "add_statementimport", "change_statementimport", "delete_statementimport", "view_statementimport",
        "add_statementline", "change_statementline", "delete_statementline", "view_statementline",
        "add_transaction", "change_transaction", "delete_transaction", "view_transaction",
        "add_checklistitemtemplate", "change_checklistitemtemplate", "delete_checklistitemtemplate", "view_checklistitemtemplate",
        "add_checklisttemplate", "change_checklisttemplate", "delete_checklisttemplate", "view_checklisttemplate",
        "add_job", "change_job", "delete_job", "view_job",
        "add_notification", "change_notification", "delete_notification", "view_notification",
        "add_task", "change_task", "delete_task", "view_task",
        "add_taskchecklistitem", "change_taskchecklistitem", "delete_taskchecklistitem", "view_taskchecklistitem",
        "add_timeentry", "change_timeentry", "delete_timeentry", "view_timeentry",
        "add_attempt", "change_attempt", "delete_attempt", "view_attempt",
        "add_course", "change_course", "delete_course", "view_course",
        "add_video", "change_video", "delete_video", "view_video",
        "add_quiz", "change_quiz", "delete_quiz", "view_quiz",
        "add_question", "change_question", "delete_question", "view_question",
        "add_lesson", "change_lesson", "delete_lesson", "view_lesson",
        "add_enrollment", "change_enrollment", "delete_enrollment", "view_enrollment",
        "add_knowledgechunk", "change_knowledgechunk", "delete_knowledgechunk", "view_knowledgechunk",
        "add_backupjob", "change_backupjob", "delete_backupjob", "view_backupjob",
        "add_backupcursor", "change_backupcursor", "delete_backupcursor", "view_backupcursor",
        "add_chunk", "change_chunk", "delete_chunk", "view_chunk",
        "add_knowledgesource", "change_knowledgesource", "delete_knowledgesource", "view_knowledgesource",
        "add_document", "change_document", "delete_document", "view_document",
        "add_citation", "change_citation", "delete_citation", "view_citation",
    ],

    "Staff": [
        # User permissions
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
     

        # Client Registration
        "add_purchaseregister", "change purchaseregister", "delete purchaseregister", "view purchaseregister",
        "add_purchasestockitem", "change purchasestockitem", "delete purchasestockitem", "view purchasestockitem",
        "add_purchaselandedexpense", "change purchaselandedexpense", "delete purchaselandedexpense", "view purchaselandedexpense",
        "add_purchaseitem", "change purchaseitem", "delete purchaseitem", "view purchaseitem",
        "add_purchasereturn", "change purchasereturn", "delete purchasereturn", "view purchasereturn",
        "add_salesdetails", "change salesdetails", "delete salesdetails", "view salesdetails",
        "add_salesfilterpreset", "change salesfilterpreset", "delete salesfilterpreset", "view salesfilterpreset",
        "add_salesstockitem", "change salesstockitem", "delete salesstockitem", "view salesstockitem",
        "add_salesreturn", "change salesreturn", "delete salesreturn", "view salesreturn",
    ]
}
